name: CI Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

env:
  IMAGE_CONFIG: 'image-config.yaml'  # Path to your image configuration file
  DOCKER_IMAGE: 'elitamsut/myapp'  # Your custom Docker image name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GITHUB_SSH_KEY }}
          ref: 'test'

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          pip install pytest-flask  # Install pytest
          pytest  # Run tests

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: ./build-docker.yml  # Reference the Docker workflow file
        with:
          IMAGE_CONFIG: ${{ env.IMAGE_CONFIG }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}

