name: CI Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

env:
  IMAGE_CONFIG: 'image-config.yaml'
  DOCKER_IMAGE: 'elitamsut/myapp'  # Your custom Docker image name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GITHUB_SSH_KEY }}
          ref: 'test'

      # Set up Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          TAG=$(yq eval '.image.tag' $IMAGE_CONFIG)
          echo "Building Docker image with tag: ${TAG}"
          docker build --pull -t ${{ env.DOCKER_IMAGE }}:${TAG} .

      # Run Tests
      - name: Run Tests
        run: |
          TAG=$(yq eval '.image.tag' $IMAGE_CONFIG)
          echo "Running tests on image: ${{ env.DOCKER_IMAGE }}:${TAG}"
          docker run --rm ${{ env.DOCKER_IMAGE }}:${TAG} python -m unittest discover -s tests

      # Log in to the elitamsut registry
      - name: Log in to elitamsut Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: 'elitamsut'  # Specify your registry here

      # Push Docker Image
      - name: Push Docker Image
        run: |
          TAG=$(yq eval '.image.tag' $IMAGE_CONFIG)
          echo "Pushing Docker image: ${{ env.DOCKER_IMAGE }}:${TAG}"
          docker push ${{ env.DOCKER_IMAGE }}:${TAG}

      # Update Helm values with new image tag
      - name: Update Helm values
        run: |
          TAG=$(yq eval '.image.tag' $IMAGE_CONFIG)
          echo "Updating Helm values with tag: ${TAG}"
          sed -i "s/tag: .*/tag: '${TAG}'/" flask-hello-world/values.yaml  # Corrected path

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install myapp path/to/your/chart --values flask-hello-world/values.yaml

      # Notify Success
      - name: Notify Success
        run: echo "CI Pipeline completed successfully!"

