name: CI Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

env:
  DOCKER_IMAGE: 'elitamsut/myapp'
  DOCKER_TAG: 'v1.0.10'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean Workspace
        run: |
          sudo rm -rf *
      
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GITHUB_SSH_KEY }}
          ref: 'test' # Branch name

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --pull -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
      
      - name: Run Tests
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} python -m unittest discover -s tests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  post:
    success:
      run: echo "CI Pipeline completed successfully! The Docker image has been pushed to Docker Hub."
    failure:
      run: echo "CI Pipeline failed."

