name: Docker Image CI

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        id: build
        run: |
          IMAGE_TAG="v1.0.$(date +%s)"  # Create a version tag based on the timestamp
          docker build . --file Dockerfile --tag elitamsut/myapp:${IMAGE_TAG}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  # Store the image tag in an environment variable

      - name: Log in to elitamsut Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: 'elitamsut'  # Specify your registry here

      - name: Push Docker Image to elitamsut Registry
        run: |
          echo "Pushing Docker image: elitamsut/myapp:${{ env.IMAGE_TAG }}"
          docker push elitamsut/myapp:${{ env.IMAGE_TAG }}  # Use the image tag from the environment variable

      - name: Notify Success
        run: echo "Docker image creation and push completed successfully!"

