name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      id: build
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag elitamsut/myapp:$TAG
        echo "::set-output name=tag::$TAG"  # Set the output tag variable

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push elitamsut/myapp:${{ steps.build.outputs.tag }}  # Use the stored tag

